export enum JobType {
  EOM_SNAPSHOT_LIMIT_USAGE = "EOM_SNAPSHOT_LIMIT_USAGE",
  EOM_RECAP_MONTHLY_SUMMARY_TO_SPREADSHEET =
    "EOM_RECAP_MONTHLY_SUMMARY_TO_SPREADSHEET",
  EOM_SEND_MONTHLY_SUMMARY = "EOM_MONTHLY_SUMMARY",
}
