name: Deploy
on:
  push:
    branches: main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v2.1

      - name: Run DB Migration
        run: deno task migrate:up

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "rogojagadal-spending-tr-78"
          entrypoint: "src/index.ts"
          root: "."
